language: julia
os:
    - linux
julia:
    - 0.5

notifications:
    email: false
git:
  depth: 999999

script:
    - julia -e 'Pkg.clone("https://github.com/samoconnor/AWSCore.jl.git")'
    - julia -e 'Pkg.clone("https://github.com/samoconnor/AWSS3.jl.git")'
    - julia -e 'Pkg.clone(pwd()); Pkg.test("S3Dicts")'
