language: julia
sudo: required
os:
    - linux
julia:
    - 0.5

notifications:
    email: false
git:
  depth: 999999

before_install:
    - sudo apt-get install hdf5-tools
script:
    - julia -e 'Pkg.update()'
    - julia -e 'Pkg.clone("https://github.com/samoconnor/AWSCore.jl.git")'
    - julia -e 'Pkg.clone("https://github.com/samoconnor/AWSS3.jl.git")'
    - julia -e 'Pkg.clone("https://github.com/seung-lab/BigArrays.jl.git")'
    - julia -e 'Pkg.clone(pwd()); Pkg.test("S3Dicts")'
